::: {.content-hidden}
$$
{{< include macros.tex >}}
$$
:::




# Preliminaries

Before introducing $\R$ we want to make sure that we cover all the basics needed for the task.

## Sets

A sets is a **collection** of objects. These objects are called **elements** of the set. For example in the previous section we mentioned the following sets:

- $\N$ the set of natural numbers
- $\Z$ the set of integers
- $\Q$ the set of rational numbers
- $\R$ the set of real numbers

Given an arbitrary set $A$, we write 
$$
x \in A
$$ 

if the element $x$ belongs to the set $A$. If an element $x$ is not contained in $A$, we say that 

$$
x \notin A \,.
$$

::: Remark

A set can contain all sorts of elements. For example the students in a classroom can be modelled by a set $S$. The elements of the set are the students. For example

$$
S = \{ 
    \text{Alice, Olivia, Jake, Sahab}   
     \}
$$

In this case we have

$$
\text{Alice} \in S 
$$
but instead

$$
\text{Silvio} \notin S \,. 
$$

:::


### Union and intersection

For two sets $A$ and $B$ we define their **union** as the set
$$
A \cup B := \{ x\, \colon \, x \in A  \, \text{ or } \, x \in B \} \,.
$$
The **intersection** of $A$ and $B$ is defined by
$$
A \cap B := \{ x\, \colon \, x \in A  \, \text{ and } \, x \in B \} \,.
$$
We denote the **empty set** by the symbol $\emptyset$. Two sets are **disjoint** if 
$$
A \cap B = \emptyset \,.
$$

::: Example

Define the subset of rational numbers
$$
S:= \left\{ x \in \Q \, \colon \, 0 < x < \frac52 \right\} \,.
$$
Then we have 
$$
\N \cap S = \{1, 2 \} \,.
$$
We can also define the sets of **even** and **odd** numbers by 

\begin{align}
E & := \{ 2n \, \colon \, n \in \N \} \,,\\
O & := \{ 2n+1 \, \colon \, n \in \N \} \,.
\end{align}

Then we have

\begin{align}
\N \cap E & = E \,, \,\, \N \cap O = O \,, \\
O \cup E & = \N \,, \,\, O \cap D = \emptyset \,.
\end{align}

:::




### Inclusion and equality


Given two sets $A$ and $B$, we say that $A$ is **contained** in $B$ if all the elements of $A$ are also contained in $B$. This will be denoted with the **inclusion** symbol $\subset$, that is,
$$
A \subset B \,.
$$
In this case we say that 

- $A$ is a **subset** of $B$, 
- $B$ is a **superset** of $A$.

The inclusion $A \subset B$ is equivalent to the implication:
$$
x \in A \,\, \implies \,\, x \in B 
$$
for all $x \in A$. The symbol $\implies$ reads **implies**, and denotes the fact that the first condition implies the second.


::: Example

Given two sets $A$ and $B$ we always have
\begin{gather}
(A \cap B) \subset A \,, \,\, (A \cap B) \subset B \,,\\
A \subset (A \cup B) \,, \,\, B \subset (A \cup B) \,.
\end{gather}

:::


We say that two sets $A$ and $B$ are equal if they contain the **same** elements. We denote equality by the symbol
$$
A=B \,.
$$


::: Example

The sets 
$$
A =\{ 1,2,3 \}
$$
and 
$$
B= \{ 3 ,1,2\}
$$
are equal. This is because they contain exactly the same elements: **order** does not matter when talking about sets. 

:::

::: {.Proposition #Proposition-Equality-Sets}

Let $A$ and $B$ be sets. Then 
$$
A=B
$$
**if and only if**
$$
A \subset B \,\, \text{ and } \,\, B \subset A \,.
$$

:::



Before proceeding with the proof, let us clarify what the expression **if and only if** mean. Suppose that you are given two statements, say $\alpha$ and $\beta$. Then 
$$
\alpha \iff \beta
$$
is equivalent to the following conditions:

- $\alpha \implies \beta$, that is, if $\alpha$ is true then also $\beta$ is true,
- $\beta \implies \alpha$, that is, if $\beta$ is true then also $\alpha$ is true.  


::: Proof
The proof is almost trivial. However it is a good exercise in basic logic, so let us do it. 


1. First implication $\implies$:  
Suppose that $A=B$. Let us show that $A\subset B$. Since $A = B$, this means that all the elements of $A$ are also contained in $B$. Therefore if we take $x \in A$ we have
$$
x \in A \,\, \implies \,\, x \in B \,.
$$
This shows $A \subset B$. The proof of $B \subset A$ is similar. 

2. Second implication $\impliedby$:  
Suppose that $A \subset B$ and $B \subset A$. We need to show $A=B$, that is, $A$ and $B$ have the same elements. To this end let $x \in A$. Since $A \subset B$ then we have $x \in B$. Thus $B$ contains all the elements of $A$. Since we are also assuming $B \subset A$, this means that $A$ contains all the elements of $B$. Hence $A$ and $B$ contain the same elements, and $A=B$.

:::


The above proposition is very useful when we need to **prove** that two sets are equal: rather than showing directly that $A = B$, we can prove that $A \subset B$ and $B \subset A$. 




### Infinite unions and intersections

Suppose given a set $\Omega$, and a family of sets $A_n \subset \Omega$, where $n \in \N$. Then we can define the **infinte union**
$$
\bigcup_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for at least one } \,\, n \in \N \} \,.
$$
The **infinte intersection** is defined as
$$
\bigcap_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for all } \,\, n \in \N \} \,.
$$

::: Example 

Let the ambient set be $\Omega:=\N$ and define the family $A_n$ by
\begin{align}
A_1 & := \{ 1, 2, 3 , 4 , \ldots \} \\
A_2 & := \{ 2, 3 , 4 , 5, \ldots \} \\
A_3 & := \{ 3 , 4 , 5, 6, \ldots \} \\
& \ldots \ldots  \\
A_n & := \{ n, n+1, n+2, n+3,  \ldots \} \,,
\end{align}
for arbitrary $n \in \N$. Then
$$
\bigcup_{n \in \N} A_n = \N \,.
$$ {#eq-infinite-union}
The above equality can be easily proven using Proposition \ref{Proposition-Equality-Sets}. Indeed, assume that $m \in \cup_n A_n$. Then $m \in A_n$ for at least one $n \in \N$. Since $A_n \subset \N$, we conclude that $m \in \N$. This shows 
$$
\bigcup_{n \in \N} A_n \subset \N \,.
$$
Conversely, suppose that $m \in \N$. By definition $m \in A_m$. Hence there exists at least one index $n$, $n=m$ in this case, such that $m \in A_n$. Then by definition $m \in \cup_{n \in \N} A_n$, showing that
$$
\N \subset \bigcup_{n \in \N} A_n \,.
$$
Hence we conclude (@eq-infinite-union) by Proposition \ref{Proposition-Equality-Sets}.  
We also have that
$$
\bigcap_{n \in \N} A_n = \emptyset \,.
$$ {#eq-infinite-intersection}
We prove the above by **contradiction**. Indeed, suppose that (@eq-infinite-intersection) is false, i.e., 
$$
\bigcap_{n \in \N} A_n \neq \emptyset \,.
$$
This means there exists some $m \in \N$ such that $m \in \cap_{n \in \N} A_n$. Hence, by definition, $m \in A_n$ for all $n \in \N$. However $m \notin A_{m+1}$, yielding a contradiction. Thus (@eq-infinite-intersection) holds.
:::




### Complement

Suppose that $A$ and $B$ are subsets of a larger set $\Omega$. The **complement** of $A$ with respect to $B$ is the set of elements of $B$ which do not belong to $A$, that is
$$
B \smallsetminus A := \{ x \in \Omega \, \colon \, x \in B \, \text{ and } \, x \notin A \} \,.
$$
In particular, the complement of $A$ with respect to $\Omega$ is denoted by 
$$
A^c := \Omega \smallsetminus A := \{ x \in \Omega \, \colon \, x \notin A \} \,.
$$


::: Remark

Suppose that $A \subset \Omega$. Then $A$ and $A^c$ form a **partition** of $\Omega$, in the sense that
$$
A \cup A^c = \Omega  \,\, \text{ and } \,\,  A \cap A^c = \emptyset \,.
$$

:::

::: Example

Suppose $A, B \subset \Omega$. Then
$$
A \subset B  \iff B^c \subset A^c \,.
$$

Let us prove the above claim:

- First implication $\implies$:  
Suppose that $A \subset B$. We need to show that $B^c \subset A^c$. Hence, assume $x \in B^c$. By definition this means that $x \notin B$. Now notice that we cannot have that $x \in A$. Indeed, assume $x \in A$.  By assumption we have $A \subset B$, hence $x \in B$. But we had assumed $x \in B$, contradiction. Therefore it must be that $x \notin A$. Thus $B^c \subset A^c$.

- Second implication $\impliedby$:  
Essentially the same proof, hence we omit it.  
:::

We conclude by stating the De Morgan's Laws, which we do not prove. 

::: Proposition
## De Morgan's Laws

Suppose $A,B \subset \Omega$. Then
$$
(A \cap B)^c = A^c \cup B^c 
$$
and
$$
(A \cup B)^c = A^c \cap B^c  \,.
$$ 

:::



### Cartesian product

Suppose $A$ and $B$ are two sets. We 

